---
version: "2.1"
services:
  pricer:
    image: pricer
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9601:3000
    environment:
      - NEXTAUTH_URL=https://pricer.sneu.date
    env_file:
      - .env
    restart: unless-stopped
